apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
  {{ include "app.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  selector:
  {{ include "app.labels" . | nindent 4 }}
ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
